spring:
 data:
   mongodb:
#     authentication-database:
     #username: ${MONGO_USER}
     #password: ${MONGO_PASSWORD}
     database: keepnote
     port: 27017
     host: localhost
server:
 port: 8082